/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DB_H_RPCGEN
#define _DB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct rec {
	int rno;
	char name[50];
	int m;
};
typedef struct rec rec;

#define DBPROGRAM 22222222
#define DBPROGVERSION 4

#if defined(__STDC__) || defined(__cplusplus)
#define insert 1
extern  int * insert_4(struct rec *, CLIENT *);
extern  int * insert_4_svc(struct rec *, struct svc_req *);
#define delete 2
extern  int * delete_4(struct rec *, CLIENT *);
extern  int * delete_4_svc(struct rec *, struct svc_req *);
#define update 3
extern  int * update_4(struct rec *, CLIENT *);
extern  int * update_4_svc(struct rec *, struct svc_req *);
#define show 4
extern  struct rec * show_4(int *, CLIENT *);
extern  struct rec * show_4_svc(int *, struct svc_req *);
extern int dbprogram_4_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define insert 1
extern  int * insert_4();
extern  int * insert_4_svc();
#define delete 2
extern  int * delete_4();
extern  int * delete_4_svc();
#define update 3
extern  int * update_4();
extern  int * update_4_svc();
#define show 4
extern  struct rec * show_4();
extern  struct rec * show_4_svc();
extern int dbprogram_4_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rec (XDR *, rec*);

#else /* K&R C */
extern bool_t xdr_rec ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DB_H_RPCGEN */
