/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "db.h"

void
dbprogram_4(char *host, int choice)
{
	CLIENT *clnt;
	int  *result_1;
	struct rec  insert_4_arg;
	int  *result_2;
	struct rec  delete_4_arg;
	int  *result_3;
	struct rec  update_4_arg;
	struct rec  *result_4;
	int  show_4_arg;
        //---------------
	
	//--------------
#ifndef	DEBUG
	clnt = clnt_create (host, DBPROGRAM, DBPROGVERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("Choice is: %d\n", choice);
	switch(choice) {
	case 1:
	  printf("Enter Roll No.:");
	  scanf("%d", &(insert_4_arg.rno));
	  printf("Enter Name.:");
	  scanf("%s", insert_4_arg.name);
	  printf("Enter Marks:");
	  scanf("%d", &(insert_4_arg.m));
	  result_1 = insert_4(&insert_4_arg, clnt);
	  if (result_1 == (int *) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	  else {
	    printf("%d records successfully inserted!\n", *result_1);
	  }
	  break;
	case 2:
	  result_2 = delete_4(&delete_4_arg, clnt);
	  if (result_2 == (int *) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	  break;
	case 3:
	  result_3 = update_4(&update_4_arg, clnt);
	  if (result_3 == (int *) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	  break;
	case 4:
	  printf("Enter the Roll no.: ");
	  scanf("%d", &show_4_arg);
	  result_4 = show_4(&show_4_arg, clnt);
	  if (result_4 == (struct rec *) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	  else if(result_4->rno == -1) {
	    printf("Record not found...\n");
	  }
	  else {
	    printf("Rno: %d\nName: %s\nMarks: %d\n", result_4->rno, result_4->name, result_4->m);
	  }
	  break;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	int choice;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
        while(1) {
	  printf("Enter choice::\n1.Insert\n2.Delete\n3.Update\n4.Show (Enter roll no)\n5.Quit\n");     
	  scanf("%d", &choice);
	  if(choice == 5)
	    break;
	  else {
	    dbprogram_4 (host, choice);
	  }
	}
	exit (0);
}
