/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "db.h"

bool_t
xdr_rec (XDR *xdrs, rec *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->rno))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->m))
		 return FALSE;
	return TRUE;
}
