/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MYPORT_H_RPCGEN
#define _MYPORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	char myhost[50];
	int start;
	int end;
};
typedef struct input input;

struct output {
	int total;
	int openports[100];
};
typedef struct output output;

#define portscanner 222222
#define portver 1

#if defined(__STDC__) || defined(__cplusplus)
#define getstatus 1
extern  struct output * getstatus_1(struct input *, CLIENT *);
extern  struct output * getstatus_1_svc(struct input *, struct svc_req *);
extern int portscanner_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getstatus 1
extern  struct output * getstatus_1();
extern  struct output * getstatus_1_svc();
extern int portscanner_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);
extern  bool_t xdr_output (XDR *, output*);

#else /* K&R C */
extern bool_t xdr_input ();
extern bool_t xdr_output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MYPORT_H_RPCGEN */
