/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "myport.h"
#include <sys/socket.h>
#include <sys/stat.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <unistd.h>
#include <string.h>
struct output *
getstatus_1_svc(struct input *argp, struct svc_req *rqstp)
{
	static struct output  result;
	int start, end, sockfd, i;
	struct sockaddr_in server_addr;
	char myhost[50];
	strcpy(myhost, argp->myhost);
	start = argp->start;
	end = argp->end;
	result.total = 0;
	server_addr.sin_family = AF_INET;
	bzero(&(server_addr.sin_zero), 8);
	inet_aton(myhost, &(server_addr.sin_addr));
	printf("Got connection\n");
	for(i = start; i <= end; i++) {
	  server_addr.sin_port = htons(i);
	  sleep(0.001);
	  if( (sockfd = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
	    perror("Create Failed\n");
	    exit(1);
	  }
	  if(connect(sockfd, (struct sockaddr *)&server_addr, sizeof(server_addr)) == -1) {
	    close(sockfd);
	  }
	  else {
	    result.openports[(result.total)++] = i;
	    close(sockfd);
	  }
	}
	(result.total)--;
	return &result;
}
