/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct InputInfo {
	int a;
	int b;
	int c;
};
typedef struct InputInfo InputInfo;

struct OutputInfo {
	int result;
};
typedef struct OutputInfo OutputInfo;

#define TEST_PROGRAM 22222222
#define TEST_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define addnums 1
extern  struct OutputInfo * addnums_1(struct InputInfo *, CLIENT *);
extern  struct OutputInfo * addnums_1_svc(struct InputInfo *, struct svc_req *);
extern int test_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addnums 1
extern  struct OutputInfo * addnums_1();
extern  struct OutputInfo * addnums_1_svc();
extern int test_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_InputInfo (XDR *, InputInfo*);
extern  bool_t xdr_OutputInfo (XDR *, OutputInfo*);

#else /* K&R C */
extern bool_t xdr_InputInfo ();
extern bool_t xdr_OutputInfo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
