/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sort.h"

struct output *
sort_1_svc(struct input *argp, struct svc_req *rqstp)
{
	static struct output  result;
	int i = 0, j = 0;
	float temp;
	int n = argp->a[0];
	for(i = 0; i < n; i++)
	  result.a[i] = argp->a[i+1];
	for(i = 1; i < n; i++) {
	  for(j = 0; j < n - i; j++) {
	    if(result.a[j] > result.a[j+1]) {
	      temp = result.a[j];
	      result.a[j] = result.a[j+1];
	      result.a[j+1] = temp;
	    }
	  }
	}
   
	return &result;
}
