/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORT_H_RPCGEN
#define _SORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	float a[25];
};
typedef struct input input;

struct output {
	float a[25];
};
typedef struct output output;

#define SORTPROG 222222
#define SORTVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define sort 1
extern  struct output * sort_1(struct input *, CLIENT *);
extern  struct output * sort_1_svc(struct input *, struct svc_req *);
extern int sortprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sort 1
extern  struct output * sort_1();
extern  struct output * sort_1_svc();
extern int sortprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);
extern  bool_t xdr_output (XDR *, output*);

#else /* K&R C */
extern bool_t xdr_input ();
extern bool_t xdr_output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORT_H_RPCGEN */
