/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDLE_H_RPCGEN
#define _IDLE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	int m;
	int n;
};
typedef struct input input;

#define IDLE 222222
#define IDLEVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define getusage 1
extern  float * getusage_1(void *, CLIENT *);
extern  float * getusage_1_svc(void *, struct svc_req *);
#define add 2
extern  int * add_1(struct input *, CLIENT *);
extern  int * add_1_svc(struct input *, struct svc_req *);
extern int idle_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getusage 1
extern  float * getusage_1();
extern  float * getusage_1_svc();
#define add 2
extern  int * add_1();
extern  int * add_1_svc();
extern int idle_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDLE_H_RPCGEN */
