/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "idle.h"

float *
getusage_1_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;
	FILE *fp;
	//system("mpstat | grep -A 5 \"%idle\" | tail -n 1 | awk -F \" \" '{print $ 12}'a > usage.txt");
	system("mpstat > usage.txt");
	fp = fopen("usage.txt", "r");
	fseek(fp, -6, SEEK_END);
	fscanf(fp, "%f", &result);
	fclose(fp);
	return &result;
}

int *
add_1_svc(struct input *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->m + argp->n;
	return &result;
}
