/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "idle.h"


void
idle_1(char *host[], int num_servers)
{
	CLIENT *clnt[20];
	float  *result_1[20];
	char *getusage_1_arg;
	int  *result_2;
	struct input  add_1_arg;
	int i, max_idle_id;
	float max_idle;
#ifndef	DEBUG
	for(i = 0; i < num_servers; i++) {
	  clnt[i] = clnt_create (host[i], IDLE, IDLEVERSION, "udp");
	  if (clnt[i] == NULL) {
	    clnt_pcreateerror (host[i]);
	    exit (1);
	  }
#endif	/* DEBUG */

	  result_1[i] = getusage_1((void*)&getusage_1_arg, clnt[i]);
	  if (result_1[i] == (float *) NULL) {
	    clnt_perror (clnt[i], "call failed");
	  } else {
	    printf("Usage of host %d is %f\n", i, (float)(*result_1[i]));
	  }
	  clnt_destroy (clnt[i]);
	}
	for(i = 0; i < num_servers; i++) {
	  if(*result_1[i] > max_idle) {
	    max_idle = *result_1[i];
	    max_idle_id = i;
	  }
	}
	printf("Max idle is host %d\n", max_idle_id);
	clnt[0] = clnt_create (host[max_idle_id], IDLE, IDLEVERSION, "udp");
	if (clnt[0] == NULL) {
	  clnt_pcreateerror (host[max_idle_id]);
	  exit (1);
	}
	add_1_arg.m = 5;
	add_1_arg.n = 9;
	result_2 = add_1(&add_1_arg, clnt[0]);
	if (result_2 == (int *) NULL) {
	  clnt_perror (clnt[0], "call failed");
	}
	else {
	  printf("The idle workstation gives answer as: %d\n", *result_2);
	}
#ifndef	DEBUG

#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host[20];
	int num_servers = argc - 1;
	int i = 0, j = 0;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
        for(i = 0; i < num_servers; i++) {
	  host[i] = argv[i+1];
	}
	idle_1 (host, num_servers);
	exit (0);
}
