/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ES_H_RPCGEN
#define _ES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	char text[256];
};
typedef struct input input;

#define ES 222222
#define ESV 1

#if defined(__STDC__) || defined(__cplusplus)
#define serverprocess 1
extern  void * serverprocess_1(struct input *, CLIENT *);
extern  void * serverprocess_1_svc(struct input *, struct svc_req *);
extern int es_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define serverprocess 1
extern  void * serverprocess_1();
extern  void * serverprocess_1_svc();
extern int es_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ES_H_RPCGEN */
