/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ES.h"
#include <sys/socket.h>
#include <sys/stat.h>
#include <netdb.h>
#include <stdio.h>

#include <string.h>
#include <stdlib.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
void
es_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	struct input  serverprocess_1_arg;
        char mybuff[256] = "\0";
	//---------------------------------
	int sockfd1;
	struct sockaddr_in server_addr, client_addr;
	char buff[256] = "\0";
	//-------------------------------
#ifndef	DEBUG
	clnt = clnt_create (host, ES, ESV, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	//--------------------------------------
	sockfd1 = socket(AF_INET, SOCK_STREAM, 0);
	//---------------------------------------
	server_addr.sin_port = htons(3000);
	server_addr.sin_family = AF_INET;
	inet_aton("127.0.0.1", &(server_addr.sin_addr));
	bzero(&(server_addr.sin_zero), 8);
	//---------------------------------------
	printf("Connect status- %d\n",connect(sockfd1, (struct sockaddr*)&server_addr, sizeof(server_addr)));
	
#endif	/* DEBUG */
        do {
	  printf("Enter text: ");
	  gets(mybuff);
	  send(sockfd1, mybuff, strlen(mybuff), 0);
	  strcpy(serverprocess_1_arg.text, mybuff);
	  printf("Sent on socket\n");
	  result_1 = serverprocess_1(&serverprocess_1_arg, clnt);
	  if (result_1 == (void *) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	  else {
	    printf("Client got (cheating): %s\n", (char *)result_1);
	    buff[recv(sockfd1, buff, 256, 0)] = '\0';
	    printf("Client got from socket: %s\n", buff);
	  }
	  sleep(7);
	} while(1);
	close(sockfd1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	es_1 (host);
exit (0);
}
